language: node_js
node_js:
  - stable
  - '0.12'
  - '0.11'
sudo: false
services:
   - rabbitmq
deploy:
  provider: npm
  email: pattyn.kurt@gmail.com
  api_key:
    secure: c9vnMtJPya3umtms38gn5vUiSVVs0T2LgIDhul607DKRxVAp4MWL59E6Nr/usGWu9VfSkND2rFXjcTqkfKMOot62/x6TWFkbaTVb7AGm8u6W2IJmIzk5ZEkdv+EReuoGEcvFJ1Umi75E8YafiolfaEB3fv8w+YP0lr/Sb2aMudvj2hC3ky5SfbWCEgzIBSPO8PTcgR9YPKV7chQzLguqTOOm0PPzURkvDfiUiIW58OXnG9z1A1BITOnM4sfwG5J74TdmYnRrXlT8vjRO9628EV6jiQLJMa46l+32go10E5dlAK4vAaJdRoxep4tO8ebArzxm4gWchGrkH7aD9EYZNPo59D8VEc1VJD8yE86WaPiSBmckM5Uq9AG15hVQGYCYmpMIPZIwn/k2JUmkfJ1GOlPCL724cMNrjs8b7pxbdcuEjjVAtct1/zCfWeMJnPzwp3qwKur3ipt3CiUyREO9iw8Y5srwuGUASui6AGyRTlk5ZN9BU9/hk21XcmbQ40byewHzJTwpi/Fe/FnCUukxU7kKqnkCDs0oHhhl48YloKXxe+/kwFGbY6iQN+Mh6G7OQgXR4fMEEc2n96xAOs9y8fWoOwsgd2SnqgqMlAo135eB58yZlRbxa75dMTgTWB8nnuC3od6iofi74svqzJ+HlOjXYXkg8LW8jnR9IrDDtsk=
  on:
    tags: true
    repo: KurtPattyn/kimmy
    branch: master
addons:
    code_climate:
        repo_token:
          secure: "CbvyP5ZC5YGU3ez8j+WZw5GkGzwPiZLlZb8/3QNQ7GgAmQtTxjB+jdCU8wJnLRnoIiwwNj7Qs5La4DPKp+kYSnaOugwlzCi0a8rg0uDIk0ZV6wCWOX4CYMdcX0giAW28+MzNObbe01Uo+WN9oefSm+Oh1ywc/HuNr+hsEy1nzMDHEFadqmrbgILfQfHOYuWlTl+IXrWYokSOrfcADMO25pNfvuJ2cSoIoe+t9+qDja+XI1E0FYiulAp7vuW6b320x2Ms/PPb2T+ojr2agfg+yr/9nHrJkrHQQhlSAoeNMtZmNUYM6rMOh+Z8p6uME6ZXDApSje5mzxL57a6QgL+qlZqT6LwHqrMLJTnwH1+eXLRaVYuQwgqzFUDjFsNQN5oIZsnKWWQVAbQX/LNMNJB0sxi2qg6eI1Cz4mLE9Y6kgxx1pLcra5FVHA9PlkxrUm3qwfhaVWa7Fu1vMaksxG0OlPzReHxW8BB3IMNjgthCgpchtq5xIFOzFwCV4aKzxLesKX8/ZTNns5p3bSGCOABMgWopNpXGMgftdjkwdgfF/68si1+fjx4wdDSyKW4BIznUBbjM3SdUENib4HhrcKd5Skya4txcBdpc4DvDPz4YCBqxzFdkgltLQuh8/ZKZTr0AQvCj0P2rIXOnMBelxHmIScMhLAPmEDoPZtc0jgr1d2w="
before_script:
  - npm run check-style
  - npm run code-analysis
script: npm run test-ci
after_success:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
  - npm install codeclimate-test-reporter && codeclimate-test-reporter < ./coverage/lcov.info
